version: '3'
services:
  msql-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: msql-dash
    volumes:
      - ./logs:/app/logs:rw
      - ../tests/data/:/app/test:rw # This is input test query data
      - ./temp:/app/temp:rw
    ports:
    - "5343:5000"
    networks:
      - default
      - nginx-net
    restart: on-failure
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: massql.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: massql.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com
    deploy:
      resources:
        limits:
          memory: 16000M


networks:
  nginx-net:
    external:
      name: nginx-net